server:
  port: 2070
  max-http-header-size: 2000000
  tomcat:
    max-http-header-size: 2000000
eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
    instance-id: page-proxy-server:2070
  client:
    serviceUrl:
      defaultZone: http://localhost:1010/eureka/
      #注册中心的注册地址 ，其他微服务需要向这个地址注册
spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    listener:
      simple:
        acknowledge-mode: manual
  application:
    name: page-proxy-server
feign:
  hystrix:
      enabled: true #开启Hystrix支持
pagestatic:
  routingkey: hrmCourseSite


