server:
  port: 1020
  max-http-header-size: 2000000
  tomcat:
    max-http-header-size: 2000000
eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
    instance-id: zuul-server:1020
  client:
    serviceUrl:
      defaultZone: http://localhost:1010/eureka/
      #注册中心的注册地址 ，其他微服务需要向这个地址注册
spring:
  application:
    name: zuul-server
#配置zuul
zuul:
  include-debug-header: true
  ignoredServices: "*" #忽略(不准)服务名方式访问
  prefix: "/hrm" #统一访问路径的前缀
  routes:
    system-server: "/sys/**"   #systemmanage-server 这个服务使用 /systemmanage路径访问
    course-server: "/course/**"   #course-server 这个服务使用 /course路径访问
    redis-server: "/redis/**"
    fastdfs-server: "/fastdfs/**"
    es-server: "/es/**"
    pager-server: "/pager/**"
  host:
    connect-timeout-millis: 5000
    socket-timeout-millis: 50000
ribbon:
  OkToRetryOnAllOperations: false #对所有操作请求都进行重试,默认false
  ReadTimeout: 5000   #负载均衡超时时间，默认值5000
  ConnectTimeout: 5000 #ribbon请求连接的超时时间，默认值2000
  MaxAutoRetries: 2     #对当前实例的重试次数，默认0
  MaxAutoRetriesNextServer: 2 #对切换实例的重试次数，默认1

hystrix:
  command:
    default:  #default全局有效，service id指定应用有效
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 5000 #断路器超时时间，默认1000ms
feign:
  hystrix:
    enabled: true
