server:
  port: 2060
  max-http-header-size: 2000000
  tomcat:
    max-http-header-size: 2000000
eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
    instance-id: pager-server:2060
  client:
    serviceUrl:
      defaultZone: http://localhost:1010/eureka/
      #注册中心的注册地址 ，其他微服务需要向这个地址注册
spring:
  application:
    name: pager-server
#集成mybatis-plus
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: 123456
    url: jdbc:mysql:///hrm-pager
    driver-class-name: com.mysql.jdbc.Driver
mybatis-plus:
  mapper-locations: classpath:com/xmh/hrm/mapper/*Mapper.xml




#feign:
#  hystrix:
#      enabled: true #开启Hystrix支持
#=======================================================================
#指向配置中心
#spring:
#  cloud:
#    config:
#      uri: http://localhost:6001
#      name: application-pay  #我需要哪个配置文件
#      profile: dev    # application-pay-dev.yml
#      #label: master